const loginActionTypes = {
	LOGIN_USER: 'LOGIN_USER',
	LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
	LOGIN_USER_FAIL: 'LOGIN_USER_FAIL',
	LOGOUT_USER: 'LOGOUT_USER',
	LOGOUT_USER_FAIL: 'LOGOUT_USER_FAIL',
	SIGNUP_USER: 'SIGNUP_USER',
	SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
};


export default {
	...loginActionTypes,
};